name: DJGoodVibrations
favicon: null
layout_spectrum: 0.5361711424775422
typography_spectrum: 0.501054157037288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8883417290635407
  lightness: 0.7067466194275767
  saturation: 0.5320609270129353
  rhythmicContrast: 0.5059734156820923
purpose: []
